### ISSUE TITLE
paramiko does not automatically add unknown hosts

### ISSUE THREAD

**Issue by onyxfish** [onyxfish/relay#11]
```
Connecting to SSH session on remote port 2222
Traceback (most recent call last):
  File "/usr/local/share/python/relay", line 9, in <module>
    load_entry_point('relay==0.0.8', 'console_scripts', 'relay')()
  File "/usr/local/lib/python2.7/site-packages/relay.py", line 187, in _main
    func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/relay.py", line 281, in ssh
    key_filename=env['pair_private_key']
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 321, in connect
    self._policy.missing_host_key(self, server_hostkey_name, server_key)
  File "/usr/local/lib/python2.7/site-packages/paramiko/client.py", line 85, in missing_host_key
    raise SSHException('Server %r not found in known_hosts' % hostname)
paramiko.SSHException: Server '[54.244.243.254]:2222' not found in known_hosts
```

**Comment by jmsalomr** [comment]
Hi,

I have the same problem. Is this a bug or I'm doing something wrong. I'm using paramiko in Python 2.7 32 bits over Windows 7.

**Comment by jmsalomr** [comment]
Sorry, solved.

You have to use:

ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy()) before

**Comment by ghost** [comment]
You need add: ssh.load_system_host_keys()  ..before ssh.connect

**Comment by anirudt** [comment]
+1 @jmsalomr , that worked. Thanks.

**Comment by anunayamar** [comment]
@jmsalomr you saved my time. Thanks!!

**Comment by zhangkaka** [comment]
even added ,problem still exsist

**Comment by zhangkaka** [comment]
![image](https://cloud.githubusercontent.com/assets/9148977/14762154/3681d0b2-09a6-11e6-8883-2b85f0af6f43.png)

**Comment by zlshi** [comment]
+1 @jmsalomr , that worked. Thanks.

**Comment by tao12345666333** [comment]
@jmsalomr  Thanks.

**Comment by AlexandreLicinio** [comment]
@jmsalomr thanks :) :+1:

**Comment by zed** [comment]
To modify `~/.ssh/known_hosts` file (to save the keys permanently) in addition to `AutoAddPolicy()`, use `client.load_host_keys(os.path.expanduser('~/.ssh/known_hosts'))`. Note: `AutoAddPolicy()` opens you to the MITM attack. See [Paramiko: Add host_key to known_hosts permanently](https://stackoverflow.com/questions/39523216/paramiko-add-host-key-to-known-hosts-permanently).

**Comment by kylefoley76** [comment]
What type of object is ssh?

**Comment by usama767** [comment]
```
import paramiko as paramiko
from paramiko import AutoAddPolicy

ssh = paramiko.SSHClient()
ssh.load_system_host_keys()
ssh.set_missing_host_key_policy(AutoAddPolicy())
ssh.connect('52.160.xx.xx', port=22, username='frt-user', password='xxxxxx',sock=None)
ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command('ls')

```

i get this error 
TypeError: 'NoneType' object is not callable


what is the step i am missing or doing wrong? @jmsalomr

**Comment by akliorin** [comment]
@usama767

I ran into both of the issues in this thread.
First, adding the autopolicy does work most of the time.

To fix the NoneType error, I went to /<user>/.ssh and deleted everything. Started working.
